name: Deploy

on:
  push:
    branches:
      - main  # или любая другая ветка, которую вы хотите использовать

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -p 22 -o StrictHostKeyChecking=no admin_63@178.161.150.241 << 'EOF'
            cd /home/admin_63/TgBot
            git pull origin main
            sudo systemctl restart aiogram_bot.service
          EOF