name: Deploy

on:
  push:
    branches:
      - main  # или любая другая ветка, которую вы хотите использовать

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to server
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no admin_63@178.161.150.241 << 'EOF'
            cd /home/admin_63/TgBot
            git pull origin main
            sudo systemctl restart aiogram_bot.service
          EOF
