name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Укажите вашу версию Python


      - name: Deploy script
        run: |
          cd /home/admin_63/TgBot
          git pull origin main
          python main.py  # Запуск вашего скрипта

